// Exercise Library
// Each exercise: id, name, muscles, sets, reps, defaultWeight, defaultReps, bodyweight, location, type

const EXERCISES = [

  // ── PUSH — GYM ──────────────────────────────────────────────────────────────
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    muscles: 'Chest mid',
    sets: 4,
    reps: '6–8',
    defaultWeight: 80,
    defaultReps: 7,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },
  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    muscles: 'Chest upper',
    sets: 3,
    reps: '8–10',
    defaultWeight: 28,
    defaultReps: 9,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },
  {
    id: 'ohp',
    name: 'Overhead Press',
    muscles: 'Shoulders',
    sets: 4,
    reps: '6–8',
    defaultWeight: 55,
    defaultReps: 7,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },
  {
    id: 'lateral-raises',
    name: 'Lateral Raises',
    muscles: 'Side delts',
    sets: 4,
    reps: '12–15',
    defaultWeight: 12,
    defaultReps: 13,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly / Pec Deck',
    muscles: 'Chest isolation',
    sets: 3,
    reps: '12',
    defaultWeight: 50,
    defaultReps: 12,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    muscles: 'Triceps',
    sets: 3,
    reps: '10–12',
    defaultWeight: 35,
    defaultReps: 11,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },
  {
    id: 'overhead-tricep-ext',
    name: 'Overhead Tricep Extension',
    muscles: 'Triceps long head',
    sets: 3,
    reps: '10',
    defaultWeight: 25,
    defaultReps: 10,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },

  {
    id: 'cable-lateral-raises',
    name: 'Cable Lateral Raises',
    muscles: 'Side delts',
    sets: 4,
    reps: '12–15',
    defaultWeight: 10,
    defaultReps: 13,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },
  {
    id: 'cable-overhead-tricep-ext',
    name: 'Cable Overhead Tricep Extension',
    muscles: 'Triceps long head',
    sets: 3,
    reps: '10–12',
    defaultWeight: 25,
    defaultReps: 11,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },
  {
    id: 'tricep-dips-gym',
    name: 'Tricep Dips',
    muscles: 'Triceps / chest lower',
    sets: 3,
    reps: '8–10',
    defaultWeight: 0,
    defaultReps: 9,
    bodyweight: false,
    location: 'gym',
    type: 'push',
  },
  {
    id: 'hang-push-gym',
    name: 'Dead Hang',
    muscles: 'Shoulder mobility / grip',
    sets: 3,
    reps: 'max hold',
    defaultWeight: null,
    defaultReps: 30,
    bodyweight: true,
    location: 'gym',
    type: 'push',
  },

  // ── PUSH — HOME ─────────────────────────────────────────────────────────────
  {
    id: 'push-ups',
    name: 'Push-Ups',
    muscles: 'Chest / triceps',
    sets: 4,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 15,
    bodyweight: true,
    location: 'home',
    type: 'push',
  },
  {
    id: 'wide-push-ups',
    name: 'Wide Push-Ups',
    muscles: 'Chest outer',
    sets: 3,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 12,
    bodyweight: true,
    location: 'home',
    type: 'push',
  },
  {
    id: 'diamond-push-ups',
    name: 'Diamond Push-Ups',
    muscles: 'Triceps',
    sets: 3,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 10,
    bodyweight: true,
    location: 'home',
    type: 'push',
  },
  {
    id: 'pike-push-ups',
    name: 'Pike Push-Ups',
    muscles: 'Shoulders',
    sets: 3,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 10,
    bodyweight: true,
    location: 'home',
    type: 'push',
  },
  {
    id: 'decline-push-ups',
    name: 'Decline Push-Ups',
    muscles: 'Upper chest',
    sets: 3,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 12,
    bodyweight: true,
    location: 'home',
    type: 'push',
  },
  {
    id: 'tricep-dips',
    name: 'Tricep Dips',
    muscles: 'Triceps',
    sets: 3,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 12,
    bodyweight: true,
    location: 'home',
    type: 'push',
  },
  {
    id: 'hang-push-home',
    name: 'Dead Hang',
    muscles: 'Shoulder mobility / grip',
    sets: 3,
    reps: 'max hold',
    defaultWeight: null,
    defaultReps: 30,
    bodyweight: true,
    location: 'home',
    type: 'push',
  },

  // ── PULL — GYM ──────────────────────────────────────────────────────────────
  {
    id: 'weighted-pull-ups',
    name: 'Pull-Ups (weighted)',
    muscles: 'Lats / width',
    sets: 4,
    reps: '6–8',
    defaultWeight: 10,
    defaultReps: 7,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    muscles: 'Lats / thickness',
    sets: 4,
    reps: '6–8',
    defaultWeight: 80,
    defaultReps: 7,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    muscles: 'Mid back',
    sets: 3,
    reps: '10',
    defaultWeight: 60,
    defaultReps: 10,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    muscles: 'Lats',
    sets: 3,
    reps: '10–12',
    defaultWeight: 65,
    defaultReps: 11,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'face-pulls',
    name: 'Face Pulls',
    muscles: 'Rear delt / rotator',
    sets: 3,
    reps: '15',
    defaultWeight: 20,
    defaultReps: 15,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'db-curl',
    name: 'Dumbbell Curl',
    muscles: 'Biceps',
    sets: 3,
    reps: '10–12',
    defaultWeight: 18,
    defaultReps: 11,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    muscles: 'Brachialis',
    sets: 3,
    reps: '10',
    defaultWeight: 18,
    defaultReps: 10,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'cable-crunch',
    name: 'Weighted Abs (Cable Crunch)',
    muscles: 'Core',
    sets: 3,
    reps: '12–15',
    defaultWeight: 40,
    defaultReps: 13,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'cable-bicep-curl',
    name: 'Cable Bicep Curl',
    muscles: 'Biceps',
    sets: 3,
    reps: '10–12',
    defaultWeight: 25,
    defaultReps: 11,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'prone-rows',
    name: 'Prone Incline Row',
    muscles: 'Rear delt / mid back',
    sets: 3,
    reps: '12',
    defaultWeight: 16,
    defaultReps: 12,
    bodyweight: false,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'pull-ups-gym',
    name: 'Pull-Ups (bodyweight)',
    muscles: 'Lats / width',
    sets: 4,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 8,
    bodyweight: true,
    location: 'gym',
    type: 'pull',
  },
  {
    id: 'hang-pull-gym',
    name: 'Dead Hang',
    muscles: 'Shoulder mobility / grip',
    sets: 3,
    reps: 'max hold',
    defaultWeight: null,
    defaultReps: 30,
    bodyweight: true,
    location: 'gym',
    type: 'pull',
  },

  // ── PULL — HOME ─────────────────────────────────────────────────────────────
  {
    id: 'pull-ups-home',
    name: 'Pull-Ups',
    muscles: 'Lats / width',
    sets: 4,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 8,
    bodyweight: true,
    location: 'home',
    type: 'pull',
  },
  {
    id: 'table-rows',
    name: 'Bodyweight Rows (table)',
    muscles: 'Mid back',
    sets: 4,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 12,
    bodyweight: true,
    location: 'home',
    type: 'pull',
  },
  {
    id: 'reverse-snow-angels',
    name: 'Reverse Snow Angels',
    muscles: 'Rear delt',
    sets: 3,
    reps: '12',
    defaultWeight: null,
    defaultReps: 12,
    bodyweight: true,
    location: 'home',
    type: 'pull',
  },
  {
    id: 'superman-hold',
    name: 'Superman Hold',
    muscles: 'Lower back / posterior',
    sets: 3,
    reps: '10',
    defaultWeight: null,
    defaultReps: 10,
    bodyweight: true,
    location: 'home',
    type: 'pull',
  },
  {
    id: 'chin-ups',
    name: 'Chin-Ups',
    muscles: 'Biceps / lats',
    sets: 3,
    reps: 'max',
    defaultWeight: null,
    defaultReps: 8,
    bodyweight: true,
    location: 'home',
    type: 'pull',
  },
  {
    id: 'towel-curl',
    name: 'Isometric Bicep Curl (towel)',
    muscles: 'Biceps',
    sets: 3,
    reps: '10',
    defaultWeight: null,
    defaultReps: 10,
    bodyweight: true,
    location: 'home',
    type: 'pull',
  },
  {
    id: 'ab-crunches',
    name: 'Ab Crunches',
    muscles: 'Core',
    sets: 3,
    reps: '20',
    defaultWeight: null,
    defaultReps: 20,
    bodyweight: true,
    location: 'home',
    type: 'pull',
  },
  {
    id: 'leg-raises',
    name: 'Leg Raises',
    muscles: 'Lower abs',
    sets: 3,
    reps: '15',
    defaultWeight: null,
    defaultReps: 15,
    bodyweight: true,
    location: 'home',
    type: 'pull',
  },
  {
    id: 'hang-pull-home',
    name: 'Dead Hang',
    muscles: 'Shoulder mobility / grip',
    sets: 3,
    reps: 'max hold',
    defaultWeight: null,
    defaultReps: 30,
    bodyweight: true,
    location: 'home',
    type: 'pull',
  },

  // ── LEGS — GYM ──────────────────────────────────────────────────────────────
  {
    id: 'back-squat',
    name: 'Barbell Back Squat',
    muscles: 'Quads / glutes',
    sets: 4,
    reps: '6–8',
    defaultWeight: 100,
    defaultReps: 7,
    bodyweight: false,
    location: 'gym',
    type: 'legs',
  },
  {
    id: 'rdl',
    name: 'Romanian Deadlift',
    muscles: 'Hamstrings / glutes',
    sets: 4,
    reps: '8',
    defaultWeight: 90,
    defaultReps: 8,
    bodyweight: false,
    location: 'gym',
    type: 'legs',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    muscles: 'Quads',
    sets: 3,
    reps: '10–12',
    defaultWeight: 160,
    defaultReps: 11,
    bodyweight: false,
    location: 'gym',
    type: 'legs',
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl (machine)',
    muscles: 'Hamstrings',
    sets: 3,
    reps: '12',
    defaultWeight: 50,
    defaultReps: 12,
    bodyweight: false,
    location: 'gym',
    type: 'legs',
  },
  {
    id: 'walking-lunges',
    name: 'Walking Lunges',
    muscles: 'Quads / glutes',
    sets: 3,
    reps: '10/leg',
    defaultWeight: 22,
    defaultReps: 10,
    bodyweight: false,
    location: 'gym',
    type: 'legs',
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise (machine)',
    muscles: 'Calves',
    sets: 4,
    reps: '15',
    defaultWeight: 80,
    defaultReps: 15,
    bodyweight: false,
    location: 'gym',
    type: 'legs',
  },

  // ── LEGS — HOME ─────────────────────────────────────────────────────────────
  {
    id: 'bw-squats',
    name: 'Bodyweight Squats',
    muscles: 'Quads / glutes',
    sets: 4,
    reps: '20',
    defaultWeight: null,
    defaultReps: 20,
    bodyweight: true,
    location: 'home',
    type: 'legs',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    muscles: 'Quads / balance',
    sets: 3,
    reps: '10/leg',
    defaultWeight: null,
    defaultReps: 10,
    bodyweight: true,
    location: 'home',
    type: 'legs',
  },
  {
    id: 'reverse-lunges',
    name: 'Reverse Lunges',
    muscles: 'Quads / glutes',
    sets: 3,
    reps: '12/leg',
    defaultWeight: null,
    defaultReps: 12,
    bodyweight: true,
    location: 'home',
    type: 'legs',
  },
  {
    id: 'glute-bridges',
    name: 'Glute Bridges',
    muscles: 'Glutes / hamstrings',
    sets: 3,
    reps: '20',
    defaultWeight: null,
    defaultReps: 20,
    bodyweight: true,
    location: 'home',
    type: 'legs',
  },
  {
    id: 'single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    muscles: 'Glutes',
    sets: 3,
    reps: '12/leg',
    defaultWeight: null,
    defaultReps: 12,
    bodyweight: true,
    location: 'home',
    type: 'legs',
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Hamstring Curl',
    muscles: 'Hamstrings',
    sets: 3,
    reps: '6',
    defaultWeight: null,
    defaultReps: 6,
    bodyweight: true,
    location: 'home',
    type: 'legs',
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    muscles: 'Calves',
    sets: 4,
    reps: '15/leg',
    defaultWeight: null,
    defaultReps: 15,
    bodyweight: true,
    location: 'home',
    type: 'legs',
  },
  {
    id: 'jump-squats',
    name: 'Jump Squats',
    muscles: 'Power / conditioning',
    sets: 3,
    reps: '10',
    defaultWeight: null,
    defaultReps: 10,
    bodyweight: true,
    location: 'home',
    type: 'legs',
  },
];

// Helper: get exercises for a given type and location
function getExercisesForSession(type, location) {
  return EXERCISES.filter(e => e.type === type && e.location === location);
}

// Helper: get exercise by id
function getExerciseById(id) {
  return EXERCISES.find(e => e.id === id) || null;
}
